Improve error logging [skip ci]

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -68,7 +68,8 @@ runs:
         {
           invalid_files=$(find '${{ inputs.directory }}' -type f \( -name '*.yml' -o -name '*.yaml' \) -print0 | xargs -0 -I {} sh -c 'yq eval "{}" >/dev/null 2>&1 || echo "{}"')
           if [ -n "$invalid_files" ]; then
-            echo "::error::❌ Invalid YAML files found: $(IFS='; '; printf '%s; ' \"${invalid_files[@]}\")"
+            inline_invalid_files=$(IFS='; '; printf '%s; ' \"${invalid_files[@]}\")
+            echo "::error::❌ Invalid YAML files found: $inline_invalid_files"
             exit 1
           fi
           
@@ -95,7 +96,8 @@ runs:
           
           invalid_files=$(find '__checkov-linter-action__/custom_policies' -type f \( -name '*.yml' -o -name '*.yaml' \) -print0 | xargs -0 -I {} sh -c 'yq eval "{}" >/dev/null 2>&1 || echo "{}"')
           if [ -n "$invalid_files" ]; then
-            echo "::error::❌ Invalid custom policy files found: $(IFS='; '; printf '%s; ' \"${invalid_files[@]}\")"
+            inline_invalid_files=$(IFS='; '; printf '%s; ' \"${invalid_files[@]}\")
+            echo "::error::❌ Invalid custom policy files found: $inline_invalid_files"
             exit 1
           fi
           
@@ -131,9 +133,10 @@ runs:
       run: |
         echo "::group::🔍 Check for Spaces in File Names"
         {
-          files_with_spaces=$(echo '${{ steps.changed-files.outputs.all_changed_files }}' | tr '"' '\n' | grep " " || true)
+          files_with_spaces=$(echo '${{ steps.changed-files.outputs.all_changed_files }}' | sed 's/" "/\n/g' | grep " " || true)
           if [ -n "$files_with_spaces" ]; then
-            echo -e "::error::❌ Files with spaces in names found: $(echo "$files_with_spaces" | paste -sd "; " -)"
+            inline_files_with_spaces=$(echo "$files_with_spaces" | sed 's/.*/"&"/' | paste -sd "; " -)
+            echo -e "::error::❌ Files with spaces in names found: $inline_files_with_spaces"
             exit 1
           fi
 
